### ISSUE TITLE
mvnx version

### ISSUE THREAD

**Issue by edscher** [alexharston/mvnx#1]
Hi there,

I have trouble opening the files. 
`KeyError: 'configuration'`
There is no 'configuration' attribute in my mvnx files. I guess it's due to an old file version (2018.2.0).
For which mvnx version is this parser made? 

best regards
ed

**Comment by alexharston** [comment]
Hi Ed, 

Strange, as I've run it successfully with MVNX files from 2018 in the past. The easiest way to fix this is either to add configuration="FullBody" into the "< subject >" tag of your MVNX files directly (should be the 4th XML tag from the top of the file), or alternatively to clone and build the library from source, and remove the references to configuration in the __init__() method of models.py. 

Let me know how you get on - will add some error handling for this in the next release when I get some time.

Best wishes,
Alex

**Comment by alexharston** [comment]
Another thing to sanity check - do your MVNX files contain the full set of exportable tags, such as joint angles, angular velocity, angular acceleration etc, or does each frame in the MVNX file just contain orientation and position? The parser is currently designed to parse the full set of features, and will error out if it doesn't find the tags it expects (this can be remedied in future releases).

**Comment by edscher** [comment]
adding values fixed the problem, but the next raised.
```
line 146, in parse_modality
frames = self.root[2][6]
IndexError: child index out of range
```
this is probably because of the missing tags for each frame... there are only position and orientation, as you assumed.
I will get mvnx files which contain all data. 

thank you for your quick answer!

**Comment by alexharston** [comment]
Ah yes, that'll definitely be it - no problem, and good luck!
