### ISSUE TITLE
IndexError: child index out of range

### ISSUE THREAD

**Issue by rupsabasu2020** [alexharston/mvnx#4]
Hello, 

I get the following error when I try to load a .mvnx file on python: 

    file = MVNX('/Users/rupsabasu/review_and_code/prog_code/Big_DataSet/Data/SDI01_indoor_11kph.mvnx')
  File "/usr/local/lib/python3.9/site-packages/mvnx/models.py", line 104, in __init__
    self.parse_all()
  File "/usr/local/lib/python3.9/site-packages/mvnx/models.py", line 199, in parse_all
    setattr(self, key, self.parse_modality(key))
  File "/usr/local/lib/python3.9/site-packages/mvnx/models.py", line 146, in parse_modality
    frames = self.root[2][6]
IndexError: child index out of range

Could you help me figure out what is going wrong?
Thanks!

**Comment by alexharston** [comment]
Hi Rupsa,

In your raw MVNX file are there only Position and Orientation values exported? This error usually occurs when that's the case. The parser is designed for MVNX files which have the full range of data exported (angular velocities, joint angles, etc) but I'll be releasing an update in a week or two to allow parsing of just files with position and orientation. Cheers, Alex

**Comment by alexharston** [comment]
This should now be resolved thanks to #5
